// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using HDD.ApplicationCore.Entities;

namespace HDD.Web.ViewModels
{
    public partial class VehicleDocuments
    {
        public string Vin { get; set; }
        public string DocumentPath { get; set; }

        public virtual RetrofitApplication VinNavigation { get; set; }
    }
}